name: aisdisplay
description: Display AIS data from NMEA VDM feed
version: 0.0.2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  cupertino_icons: ^0.1.2
  scoped_model:
  nmea:
    git:
      url: https://github.com/jamesdalby/nmea.git
  ais:
    git:
      url: https://github.com/jamesdalby/ais.git
  vector_math:
  sqflite:
  google_maps_flutter: ^0.5.30

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
