name: aisdisplay
description: Display AIS data from NMEA VDM feed
version: 0.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  cupertino_icons: ^1.0.5
  scoped_model:
  nmea:
    git:
      url: https://github.com/jamesdalby/nmea.git
      ref: master
  ais:
    git:
      url: https://github.com/jamesdalby/ais.git
      ref: master
  vector_math:
  sqflite:
  intl: ^0.18.0
#  google_maps_flutter: ^2.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
